In [10]:
person = {'name' : '홍길동', 'age' : 10}
# 요소 추가
person['gender'] = '남자'
print(person)
# 요소 수정
person['age'] = 20
print(person)
# 요소 삭제
del person['gender']
print(person)
# 함수, 메소드 설명보기 => help함수 이용
help(person.clear)

{'name': '홍길동', 'age': 10, 'gender': '남자'}
{'name': '홍길동', 'age': 20, 'gender': '남자'}
{'name': '홍길동', 'age': 20}
Help on built-in function clear:

clear(...) method of builtins.dict instance
    D.clear() -> None.  Remove all items from D.

In [25]:
# 딕셔너리에서 키 값 가져오기
print(person.keys())

# 타입 확인하기 내장함수 type() 사용
print(type(person.keys()))

print('=' * 20)

# 딕셔너리에서 값만 가져오기
print(person.values())
print(type(person.values()))

print('=' * 20)

# 딕셔너리에서 아이템(키, 값 쌍으로) 가져오기
print(person.items())
print(type(person.items()))

print('=' * 20)

# 딕셔너리의 key, values, 아이템 순회하기
for k in person.keys() :
  print(k)
print('=' * 20)
for v in person.values() :
  print(v)
print('=' * 20)
for i in person.items() :
  print(i)
print('=' * 20)

# 아이템 순회하기 (개별변수로 받아내기)
for k, v in person.items():
  print(f'{k} - {v}')

# 튜플 개별 변수에 저장하기
name, age, gender = ('홍길동', 30, '남자')
print(name, age, gender)

dict_keys(['name', 'age'])
<class 'dict_keys'>
====================
dict_values(['홍길동', 20])
<class 'dict_values'>
====================
dict_items([('name', '홍길동'), ('age', 20)])
<class 'dict_items'>
====================
name
age
====================
홍길동
20
====================
('name', '홍길동')
('age', 20)
====================
name - 홍길동
age - 20
홍길동 30 남자

In [41]:
print(person['name'])
print(person.get('name'))
# print(person['gender'])
print(person.get('gender'))
print(person.get('gender', '남자'))

print('=' * 20)

# 딕셔너리에 키 존재 여부 확인 in
print('name' in person)
print('gender' in person)

홍길동
홍길동
None
남자
====================
True
False

In [48]:
# 집합자료형 Set(세트) 연습
s1 = { 1, 2, 3 }
s2 = set( [3, 4, 5] )
print (s1, s2)
print('=' * 20)

# 교집합
intersection = s1 & s2
print(intersection)
print('=' * 20)

# 차집합
difference = s1 - s2
print(difference)
print('=' * 20)

# 합집합
union = s1 | s2
print(f'합집합 {union}')

{1, 2, 3} {3, 4, 5}
====================
{3}
====================
{1, 2}
====================
합집합 {1, 2, 3, 4, 5}

In [50]:
# 문제) 아래 리스트 요소의 중복을 제거한 리스트를 구하시오
list1 = [2, 2, 3, 3, 4, 4, 5, 5]

# 답) SET으로 바꿨다가 => List로 변경 => list(set(list1))
result = set(list1)
print(result)
print('=' * 20)
finalResult = list(result)
print(finalResult)

{2, 3, 4, 5}
====================
[2, 3, 4, 5]

In [52]:
# 스칼라값이라고 하더라도 변수는 주소에 저장됨
x = 10
print(x)
id(x)

# 자바에서는 ==로 주소값을 비교했던 것을 파이썬에서는 is를 사용

10

140112400433680

In [53]:
def sum(x, y) :
  result = x + y
  return result

print(sum(10, 20))

30

In [58]:
def calculate(x, y) :
  add = x + y
  difference = x - y
  multifly = x * y
  mod = x // y
  remain = x % y
  return add, difference, multifly, mod, remain

print(type(calculate(10, 3)))
print(calculate(10, 3))

add, difference, multifly, mod, remain = calculate(10, 3)
print(add, difference, multifly, mod, remain)

<class 'tuple'>
(13, 7, 30, 3, 1)
13 7 30 3 1

In [65]:
pocket = ['paper', 'cellphone', 'money']
if 'money' in pocket :
  print("택시를 타고 가라")
else :
  print("걸어가라")

pocket = ['paper', 'money', 'cellphone']
if 'money' in pocket :
  pass
else:
  print("카드를 꺼내라")

택시를 타고 가라

In [66]:
# for문의 range를 이용하여 1부터 100까지 합을 구하기
sum = 0
for num in range(1, 100+1) :
  sum += num
print(f'sum={sum}')

sum=5050

In [75]:
# 문제) 1~100까지 정수 중에 짝수의 합과 홀수의 합을 각각 구하시오

sum_even = 0 ; sum_odd = 0

for num in range(1, 100+1) :
  if (num % 2 == 0) :
    sum_even += num
  else :
    sum_odd += num

print(f'짝수의 합 : {sum_even}')
print(f'홀수의 합 : {sum_odd}')

짝수의 합 : 2550
홀수의 합 : 2500

In [83]:
# 문제) 구구단 출력하기 2~9단까지 중첩 for문 이용

for i in range(2, 10) :
  print(f'====={i}단=====')
  for j in range(1, 10) :
    # result = i * j
    # print(f'{i} X {j} = {"%2d" % result}')
    print(f'{i:2} X {j:2} = {i * j :2}') # 2자리씩 주게하는 방법

=====2단=====
 2 X  1 =  2
 2 X  2 =  4
 2 X  3 =  6
 2 X  4 =  8
 2 X  5 = 10
 2 X  6 = 12
 2 X  7 = 14
 2 X  8 = 16
 2 X  9 = 18
=====3단=====
 3 X  1 =  3
 3 X  2 =  6
 3 X  3 =  9
 3 X  4 = 12
 3 X  5 = 15
 3 X  6 = 18
 3 X  7 = 21
 3 X  8 = 24
 3 X  9 = 27
=====4단=====
 4 X  1 =  4
 4 X  2 =  8
 4 X  3 = 12
 4 X  4 = 16
 4 X  5 = 20
 4 X  6 = 24
 4 X  7 = 28
 4 X  8 = 32
 4 X  9 = 36
=====5단=====
 5 X  1 =  5
 5 X  2 = 10
 5 X  3 = 15
 5 X  4 = 20
 5 X  5 = 25
 5 X  6 = 30
 5 X  7 = 35
 5 X  8 = 40
 5 X  9 = 45
=====6단=====
 6 X  1 =  6
 6 X  2 = 12
 6 X  3 = 18
 6 X  4 = 24
 6 X  5 = 30
 6 X  6 = 36
 6 X  7 = 42
 6 X  8 = 48
 6 X  9 = 54
=====7단=====
 7 X  1 =  7
 7 X  2 = 14
 7 X  3 = 21
 7 X  4 = 28
 7 X  5 = 35
 7 X  6 = 42
 7 X  7 = 49
 7 X  8 = 56
 7 X  9 = 63
=====8단=====
 8 X  1 =  8
 8 X  2 = 16
 8 X  3 = 24
 8 X  4 = 32
 8 X  5 = 40
 8 X  6 = 48
 8 X  7 = 56
 8 X  8 = 64
 8 X  9 = 72
=====9단=====
 9 X  1 =  9
 9 X  2 = 18
 9 X  3 = 27
 9 X  4 = 36
 9 X  5 = 45
 9 X  6 = 54
 9 X  7 = 63
 9 X  8 = 72
 9 X  9 = 81

In [91]:
# 문제) 단수를 입력받아 해당 구구단을 출력하시오.

dansu = int(input('단수를 입력하세요 : '))
# print(type(dansu)) # String 타입

for num in range(1, 9+1) :
  print(f'{dansu : 2} X {num : 2} = {dansu * num :>2}')

단수를 입력하세요 : 3
 3 X  1 =  3
 3 X  2 =  6
 3 X  3 =  9
 3 X  4 = 12
 3 X  5 = 15
 3 X  6 = 18
 3 X  7 = 21
 3 X  8 = 24
 3 X  9 = 27

In [96]:
def sum_all(*args):
  print(type(args))

  for ele in args:
    print(ele)

sum_all(1, 2, 3)

<class 'tuple'>
1
2
3

In [121]:
# 가변인자 :   *:튜플, **:딕셔너리
def sum_all2(*args1, **args2):
  print(type(args1))
  print(type(args2))

  for ele in args1:
    print(ele)
  print('='*20)

  for key in args2.keys():
    print(key)
  print('='*20)
  for key, val in args2.items():
    print(key, val)

print('★★★★★★Case1)호출★★★★★★')
sum_all2(1, 2, 3, name='홍길동', age=10, gender='남자')

x = (1, 2, 3)                                     # 튜플
y = {'name':'홍길동', 'age':10, 'gender':'남자'}  # 딕셔너리
print('★★★★★★Case2)호출★★★★★★')
sum_all2(*x, **y)   # 이렇게 호출해도 됨

★★★★★★Case1)호출★★★★★★
<class 'tuple'>
<class 'dict'>
1
2
3
====================
name
age
gender
====================
name 홍길동
age 10
gender 남자
★★★★★★Case2)호출★★★★★★
<class 'tuple'>
<class 'dict'>
1
2
3
====================
name
age
gender
====================
name 홍길동
age 10
gender 남자

In [127]:
g_var = 100     #전역변수 : 함수 밖에 선언 된 변수

def f(p_var=300):        #매개변수 : 함수내에서 지역변수 처럼 사용 됨
  l_var = 200   #로컬변수 : 함수 내에 선언 된 변수
  global g_var

  print(g_var) # 100
  g_var = 400

  print(g_var) # 400

  print(p_var) # 300

  print(l_var) # 200


f()

100
400
300
200

In [128]:
def sum(x, y) :
  return x + y
print(sum(10, 20))

sum2 = lambda x, y : x + y
print(sum2(20, 30))

30
50

In [138]:
list = [1, 2, 3]
list2 = []
for ele in list :
  list2.append(ele*2)

print(list2)

print('='*20)

def mul(x) :
  return x * 2

result = map(lambda x : x*2, list2)
for ele in result :
  print(ele)

print('='*20)

result2 = map(mul, list2)
for ele in result2 :
  print(ele)

[2, 4, 6]
====================
4
8
12
====================
4
8
12

In [148]:
f = open("test.txt", 'w')
for i in range(1, 11):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()