In [1]:
import pandas as pd                # 데이터 분석을 위해 pandas
import numpy as np                 # 수치계산을 위해 numpy
import matplotlib.pyplot as plt    # 시각화를 위해 mapplotlib, seaborn를 불러온다.
import seaborn as sns
import folium                      # 지도 시각화를 위한 라이브러리
import json

# 한글 설정 & 마이너스 표시
plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False)

In [21]:
# CSV 파일 읽기
df = pd.read_csv('data/housing_data.csv', encoding='cp949')

In [22]:
df

,행정구역별(시도),연령대,가구구분,2020,2020.1,2020.2,2020.3,2020.4,2020.5,2020.6,2020.7,2020.8,2020.9,2020.10,2020.11
0,행정구역별(시도),연령대,가구구분,가구-계,반려동물미보유가구-계,반려동물보유가구-계,단일-계,단일-개,단일-고양이,단일-기타,복합-계,복합-개+고양이,복합-개+기타,복합-고양이+기타,복합-개+고양이+기타
1,전국,계,계,20926710,17797748,3128962,2970999,2268514,571045,131440,157963,139644,11787,3060,3472
2,동부,계,계,16898553,14567149,2331404,2234509,1651735,471844,110930,96895,86821,5986,2482,1606
3,읍부,계,계,2022526,1679440,343086,322110,253849,55846,12415,20976,18411,1681,313,571
4,면부,계,계,2005631,1551159,454472,414380,362930,43355,8095,40092,34412,4120,265,1295
5,서울특별시,계,계,3982290,3484177,498113,479284,344419,110065,24800,18829,16740,1190,602,297
6,부산광역시,계,계,1405037,1220755,184282,176379,129190,39051,8138,7903,7182,434,201,86
7,대구광역시,계,계,985816,865720,120096,115381,86371,23450,5560,4715,4291,279,76,69
8,인천광역시,계,계,1147200,952813,194387,185412,143348,34515,7549,8975,8025,602,170,178
9,광주광역시,계,계,599217,524718,74499,71404,52779,15487,3138,3095,2786,175,106,28
10,대전광역시,계,계,631208,551052,80156,77038,56910,16081,4047,3118,2693,241,125,59
11,울산광역시,계,계,444087,384845,59242,56391,41040,12425,2926,2851,2484,175,87,105
12,세종특별자치시,계,계,139106,120612,18494,17342,12641,3557,1144,1152,997,81,35,39
13,경기도,계,계,5098431,4236258,862173,820178,623960,157807,38411,41995,37607,2762,845,781
14,강원도,계,계,661039,547395,113644,105921,86273,16121,3527,7723,6707,752,70,194
15,충청북도,계,계,678922,569226,109696,103106,82132,16736,4238,6590,5692,624,81,193
16,충청남도,계,계,892222,734862,157360,145854,115810,24638,5406,11506,10025,1092,64,325
17,전라북도,계,계,755575,645814,109761,103238,83750,15846,3642,6523,5626,598,91,208
18,전라남도,계,계,761518,624566,136952,127438,107247,16897,3294,9514,8230,900,77,307
19,경상북도,계,계,1131819,962160,169659,159417,129626,23756,6035,10242,8861,926,184,271
20,경상남도,계,계,1350155,1150659,199496,188262,141713,38206,8343,11234,9936,808,231,259
21,제주특별자치도,계,계,263068,222116,40952,38954,31305,6407,1242,1998,1762,148,15,73

In [24]:
new_column = df.iloc[0]
df.columns = new_column
df

,행정구역별(시도),연령대,가구구분,가구-계,반려동물미보유가구-계,반려동물보유가구-계,단일-계,단일-개,단일-고양이,단일-기타,복합-계,복합-개+고양이,복합-개+기타,복합-고양이+기타,복합-개+고양이+기타,NaN
0,행정구역별(시도),연령대,가구구분,가구-계,반려동물미보유가구-계,반려동물보유가구-계,단일-계,단일-개,단일-고양이,단일-기타,복합-계,복합-개+고양이,복합-개+기타,복합-고양이+기타,복합-개+고양이+기타,NaN
1,전국,계,계,20926710,17797748,3128962,2970999,2268514,571045,131440,157963,139644,11787,3060,3472,NaN
2,동부,계,계,16898553,14567149,2331404,2234509,1651735,471844,110930,96895,86821,5986,2482,1606,NaN
3,읍부,계,계,2022526,1679440,343086,322110,253849,55846,12415,20976,18411,1681,313,571,NaN
4,면부,계,계,2005631,1551159,454472,414380,362930,43355,8095,40092,34412,4120,265,1295,NaN
5,서울특별시,계,계,3982290,3484177,498113,479284,344419,110065,24800,18829,16740,1190,602,297,NaN
6,부산광역시,계,계,1405037,1220755,184282,176379,129190,39051,8138,7903,7182,434,201,86,NaN
7,대구광역시,계,계,985816,865720,120096,115381,86371,23450,5560,4715,4291,279,76,69,NaN
8,인천광역시,계,계,1147200,952813,194387,185412,143348,34515,7549,8975,8025,602,170,178,NaN
9,광주광역시,계,계,599217,524718,74499,71404,52779,15487,3138,3095,2786,175,106,28,NaN
10,대전광역시,계,계,631208,551052,80156,77038,56910,16081,4047,3118,2693,241,125,59,NaN
11,울산광역시,계,계,444087,384845,59242,56391,41040,12425,2926,2851,2484,175,87,105,NaN
12,세종특별자치시,계,계,139106,120612,18494,17342,12641,3557,1144,1152,997,81,35,39,NaN
13,경기도,계,계,5098431,4236258,862173,820178,623960,157807,38411,41995,37607,2762,845,781,NaN
14,강원도,계,계,661039,547395,113644,105921,86273,16121,3527,7723,6707,752,70,194,NaN
15,충청북도,계,계,678922,569226,109696,103106,82132,16736,4238,6590,5692,624,81,193,NaN
16,충청남도,계,계,892222,734862,157360,145854,115810,24638,5406,11506,10025,1092,64,325,NaN
17,전라북도,계,계,755575,645814,109761,103238,83750,15846,3642,6523,5626,598,91,208,NaN
18,전라남도,계,계,761518,624566,136952,127438,107247,16897,3294,9514,8230,900,77,307,NaN
19,경상북도,계,계,1131819,962160,169659,159417,129626,23756,6035,10242,8861,926,184,271,NaN
20,경상남도,계,계,1350155,1150659,199496,188262,141713,38206,8343,11234,9936,808,231,259,NaN
21,제주특별자치도,계,계,263068,222116,40952,38954,31305,6407,1242,1998,1762,148,15,73,NaN